version: '3.3'
services:
  unpub:
    build: ./
    container_name: unpub_release
    restart: always
    ports:
      - 4006:4006
    volumes: 
      - ~/.unpub-packages_release:/app/unpub-packages
    depends_on:
      - mongo
  mongo: 
    image: mongo:4.2.19
    container_name: unpub_mongo_release
    restart: always
    volumes: 
      - ~/.unpub_mongo_release:/data/db